name: Webhook Handler

on:
  repository_dispatch:
    types: "test-trigger

jobs:
  handle-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Print webhook payload
        run: |
          echo "Webhook received"
          echo '${{ github.event.client_payload }}'

      - name: Do something
        run: |
          echo "Running my webhook logic..."
