name: Webhook Handler

on:
  repository_dispatch:
    types:
      - test-trigger

jobs:
  handle-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Print webhook payload
        env:
          ARTIFACT: ${{ github.event.client_payload.artifact }}
          ENTITY: ${{ github.event.client_payload.entity }}
          PROJECT: ${{ github.event.client_payload.project }}
          COLLECTION: ${{ github.event.client_payload.collection }}
          AUTOMATION: ${{ github.event.client_payload.automation_name }}
        run: |
          echo "Artifact: $ARTIFACT"
          echo "Entity: $ENTITY"
          echo "Project: $PROJECT"
          echo "Collection: $COLLECTION"
          echo "Automation: $AUTOMATION"
